version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Change this based on your application (python: 3.9, java: corretto11, etc.)
    commands:
      - echo Install phase started on `date`
      # Add any installation commands here

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      # Add any pre-build commands here (like running tests)

  build:
    commands:
      - echo Build phase started on `date`
      # Add your build commands here
      # For Node.js: npm run build
      # For Python: pip install -r requirements.txt
      # For Java: mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  # Exclude files you don't want in the deployment package
  exclude-paths:
    - node_modules/**/* # Uncomment if Node.js
    - .git/**/*
    - .github/**/*
    - "*.md"
