version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Install phase started on `date`
      - npm ci # or `npm install` if you prefer

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - npm run prisma:generate # if you're using Prisma

  build:
    commands:
      - echo Build phase started on `date`
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  exclude-paths:
    - node_modules/**/*
    - .git/**/*
    - .github/**/*
    - "*.md"
